### ISSUE TITLE
Adapter crashes occasionally

### ISSUE THREAD

**Issue by nemodil** [Apollon77/ioBroker.homekit-controller#166]
Hi, I've been using the HomeKit Controller Adapter v. 0.4.4 for a few months now without any problems :-)
Unfortunately, the instance crashes occasionally, about once every 1-2 weeks.
After a restart, everything runs normally again.
Here is my log from today.

[iobroker.2022-06-05.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/8839825/iobroker.2022-06-05.log)

**Comment by Apollon77** [comment]
In fact I do not see any crash ... Yes it is right that it seems that the device stops to answer and it gives timeouts ... I can try to detect that and somehow start over ... What you could do as workaround would be to configure an adapter restart interval and maybe restart the adapter once a week or such ... I will see what I can do

**Comment by nemodil** [comment]
Ok, thanks!

**Comment by Apollon77** [comment]
If you like please install GitHub version of the adapter ... then try how it is there. It should reinitialize after 10 timeouts (honestly .. untested :-) )

**Comment by nemodil** [comment]
OK, I've installed it right now. I'll keep you updated. Thanks!

**Comment by Apollon77** [comment]
The poll error now have a counter number in brackets and when it reaches 11 then you should see "Device ${device.id} had too many errors, reinitialize connection" and a reconnection occurs ... so that you know what to look for in the logs

**Comment by nemodil** [comment]
It works :-) Thanks a lot!

[iobroker.2022-06-06.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/8844536/iobroker.2022-06-06.log)

**Comment by Apollon77** [comment]
Cool, I will lower it to 3 for the release. Please do me one more favor, I saw that linme too in your logs:

> 2022-06-06 12:55:03.334  - [32minfo[39m: homekit-controller.0 (15210) State value to set for "homekit-controller.0.IP-76:90:23:57:BD:54.2.sensor-carbon-dioxide-14.carbon-dioxide-detected" has to be type "number" but received type "boolean" 

Please delete this object and restart the adaopter ... it should be recreated ... does the error then comes back?

**Comment by nemodil** [comment]
Same thing...
Here's the log and the created object.

[Log and created object.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/8846262/Log.and.created.object.txt)

**Comment by Apollon77** [comment]
WTF ... now I do not understand anything :-)

Can you please do one thing:
* delete that one object again
* stop adapter
* install from github again
* open an ssh shell an execute `iob debug homekit-controller.0'
* post output 

I added some logs theat hopefully help me to understand why the type remapping is not working.Thank you!

**Comment by Apollon77** [comment]
Cool, seehr interessant ... versuchste bitte nochmal mit neuester Version, würde gern das gleiche Log nochmal nehmen

**Comment by nemodil** [comment]
Bitte schön
[iob debug homekit-controller.0. 2022-06-07 2.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/8856478/iob.debug.homekit-controller.0.2022-06-07.2.log)

**Comment by nemodil** [comment]
Danke auch!
