### ISSUE TITLE
[Feature request] Implement queue to avoid overload of Homekit Bridges/Devices

### ISSUE THREAD

**Issue by DutchmanNL** [Apollon77/ioBroker.homekit-controller#180]
Background:

The HomeKit-Controller sends every state change immediately to the corresponding Homekit devices.
In most cases this works absolutely perfect and I am very happy yo have this adapter :)

But we also have situation where where homekti devices are used as a bridge, for example integrations to 1-home, loon or equal.
In that case not 1 (or maybe 3) states are attached to 1 HomeKit device, but we can for example implement up to 149 lights.
(example 1-home to KNX, alle lights are read from KNX and exposed as 1 Homekit device with al their relate light states.

Issue:
When multiple states are switched, like all lights in the mentioned scenario above, the Homekit gateway (not this adapter!) hangs up and get session timeouts. This is a well known behavior and no relation with this adapter.
We can reproduce this situation by adding the Device directly to HomeKit instead of this adapter, switching than all lights also cause a hangup.

Possible solution:
I execute multiple stress tests to identify the problem and how we could avoid that. By doing that, I figured out that an delay of 200-300ms between the switch actions helps to avoid this situation.

Feature request:
Add capability to the adapter if multiple states are triggered for 1 Homekit connected device/bridge a queue should be handled by (most happy if configurable) 200-300 ms between the different switch states.

I was able te reproduce a 100% stable situation by scripting, instead of change all the states at once having a 200ms between each change.

Why should we do that:
When integrating these kind of states to Alexa, google or HomeKit as example and you say "Turn all the lights of".... its just fired to the bridge in milliseconds which cause the connection to fail. Having this kind of queuing implemented would avoid this situation.

**Comment by Apollon77** [comment]
@DutchmanNL was that issue solved at the end because of that misconfig or is it still left?

**Comment by DutchmanNL** [comment]
> @DutchmanNL was that issue solved at the end because of that misconfig or is it still left?

It was still left, just a matter of overload for 1-home bridge I think 😅
