### ISSUE TITLE
Connection to Homekit Hub is unstable, if polling interval is set to low device gets timeout and cannot reconnect

### ISSUE THREAD

**Issue by DutchmanNL** [Apollon77/ioBroker.homekit-controller#181]
When using a Homekit like bridge, like 1-Home or other integrations handling multiple devices, the connection is dropped frequently depending on setting of the polling interval.

Example: 

Polling every 30 second, stability for 30 minutes than we get a timeout
Polling every 120 second, stability for 1 hour than we get a time out
Polling every 180 seconds, adapter is stable for several hours but at a certain moment also gets a connection time out.

In most cases the connection is picked up again automatically, but after a while (like 10 automated reconnects, it's keeps failing by timeout with error message:

```
Device  xxxx data polling failed (48): Timeout
Device  xxxx had too many errors, reinitialize connection
xxxx Device initialization already in progress ... ignore call
```

21:15:50 : adapter got disconnected
22:40:30 : Reboot of adapter did restore the connection as it did not recover by itself

debug log of 5 minutes before up to 5 minutes after send to developer in private message du to content of information

I send 2 debug logs today, the behavior above is that last log and below the step I did for the first one : 

12.17 = adapter start
12.18 = set value to all lights (53) with delay of 100ms between each call
awaiting polling of 180sec

12.22 = Values of lights are correct after polling (were incorrect before but ack true)
12.28 = adapter reboo
12.29 = set value to all lights (53) with delay of 100ms between each call lights did not respond
12.31 = polling, values are incorrect
12.31 = set value on a shutter, execution successfully
12.32 = set value on a shutter, execution successfully
12.33 = set value on 1 light, execution successfully
12.34.07 = Polling, values incorrect (not reflecting reality
Adapter reboot, afteer reboot values ar incorrect (see relation to issue #182 
12.40 = set value to all lights (53) with delay of 100ms between each call lights did not respond

Please not, al actions are executed with setting ```usePersistentCOnnections = false```
When I set the option to true and set all 50 lights in one go.... nothing gets executed and the connected bridge even looks o hangup (needed reboot of the device to get proper behavior again)

**Comment by Apollon77** [comment]
Is the topic still relevant?

**Comment by DutchmanNL** [comment]
> Is the topic still relevant?

Not for me and looks like I was the only one having this issue 🤭
