### ISSUE TITLE
Adapter set values as default instead of initial value

### ISSUE THREAD

**Issue by DutchmanNL** [Apollon77/ioBroker.homekit-controller#182]
When I start the adapter, connected to a bridge with multiple devices, I get first default values at the state objects (previous existing al always overwritten).
It needs 1 or 2 polling interfaalls before th correct data is loaded.

Example : Temps sensor are all set to 20 or 25 degrees instead of real value

Debug informatie of adapter boots is send to developer in private message

**Comment by DutchmanNL** [comment]
Sxcreenshot of datapoint logging, reboot was at
<img width="1617" alt="Schermafbeelding 2022-07-03 om 00 54 03" src="https://user-images.githubusercontent.com/7318445/177018227-54ef79db-5999-41c8-893d-0d578420820f.png">

**Comment by Apollon77** [comment]
@DutchmanNL I would have no idea why that happens ... do you have a debug log please of such a case?

**Comment by DutchmanNL** [comment]
> @DutchmanNL I would have no idea why that happens ... do you have a debug log please of such a case?

Sorry but no I switched to different implementation 😔

**Comment by Apollon77** [comment]
Ok, without debug log or ither reports I close
