### ISSUE TITLE
Adapter shows connection state FALSE due to timeout, but values are still coming in and devices can be controlled

### ISSUE THREAD

**Issue by DutchmanNL** [Apollon77/ioBroker.homekit-controller#183]
The connections state indicates false positives after a Time out or miscommunication.
In the behavior I observed, the connection states was false for about 50 minutes.

As visible in this monitoring, connection is FALS but temp and motion sensor still submit their values

<img width="1164" alt="Schermafbeelding 2022-07-03 om 00 45 44" src="https://user-images.githubusercontent.com/7318445/177018111-8879e113-e4c1-4892-8987-9e741d1093b0.png">
 
But during that time I still received values of motion and temperature sensor, after sending a switch command the adapter switch to connection state true 

Debug logging send to developer

**Comment by Apollon77** [comment]
The question is how to define "offline" if subscriptions work but other requests fail ... is it then online or not? ;-)

**Comment by Apollon77** [comment]
Ok, GitHub version adresses this topic hopefully
