### ISSUE TITLE
Only polling new values if adapter is restarted

### ISSUE THREAD

**Issue by ronschd** [Apollon77/ioBroker.homekit-controller#255]
Hey,

first, thank you for developing this adapter!

I use it with the new IKEA Dirigera and it's working.
Only problem is, that the values are only updated, if I restart des instance of the adapter ?
Is this a known issue ?
Do I have to configure something different maybe ?

Regards and thank you for all the work,
Ronald

**Comment by Apollon77** [comment]
The adapter nroamly subscribes to all states that allow subscriptions for real time updates and polls all the others in the defined interval from the adapter configuration ... Please check these setting. if it still do not work please set the loglevelto debug and post a debug log as file attachement here (taken from logfile at /opt/iobroker/log/... ) ideally from start until 2-3 times the set polling interval

**Comment by ronschd** [comment]
Hello,

thank you for your fast response.

I started the adapter with loglevel debug. I attached the output.
As I can see ther is some polling every 30 seconds, but the values don't arrive in the iobroker objects.

regards,
Ronald

[debug.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10369645/debug.log)

**Comment by Apollon77** [comment]
> but the values don't arrive in the iobroker objects.

Yes, but I also see no changes in these values ... Because of polling can not decide if value was updated or such the adapter do not update unchanged values.

When values change you would see a debug log like in your log" State ... changed ..."

So do you also have a log with a changed value? ;-)

But in general it is bad that Ikea do not seem to allow subscriptions to a singe state :-( Thats bad, so it seems that only polling works :-(

**Comment by Apollon77** [comment]
ahhh ok .... sttooop ... thats wrong ... the reads gve an error for these relevant startes (but they should also tried to be subscribed) ... Resource does not exist. ... wtf ... 

One question: If you try to remove pairing from ioBroker and pair with an iOS device ... does then anything works? Or also not?

**Comment by ronschd** [comment]
Doesn't sound too good.
Only thing I know at the moment is, as I restart the adapter instance I get all the values.

Hmm, I could try pair it with an iPad.

**Comment by Apollon77** [comment]
In fact:
* Reading "the complete data structure" seems to work fine (this is why you get all values on start). Subscriptions are returning a "partially failed "response and getting values returns "partially ressource does not exist" error sbut the respiurces queried indeed exist.
So it would be strang eif ios works ...

For me that sounds more like a FW bug of the Ikea hub and should be reported there ...

I Also got such a hub some days ago (with just a switch on it) ... need to install then I can also verify ...

**Comment by ronschd** [comment]
Ok, i paired it with the iPad.
There it works totally fine.
Even if I control the window shades with the buttons i immediately get the states on the iPad.

**Comment by Apollon77** [comment]
grmmppfff ... No idea ... Need to look into that ...

**Comment by ronschd** [comment]
If I can help or test something, please let me know.

Btw. Setup is 
Dirigera Hub
2 FYRTUR Verdunklungsrollo with the included two remotes

**Comment by Apollon77** [comment]
Kurz vorm einschlafen hatte ich eine Vermutung die sich bestätigt hat .., überlege was ich tue als Fix

**Comment by ronschd** [comment]
Klingt ja prinzipiell gut.
Kann ich irgendwie unterstützen ?

**Comment by Apollon77** [comment]
Melde mich wenn es ums Testing geht

**Comment by ronschd** [comment]
Passt, danke!

**Comment by Apollon77** [comment]
Ok, dann installiere bitte mal den Adapter von GitHub. VORHER bitte Hub unrpairen! Dann Adapter stoppen alle angelegten Objekte in ioBroker des ikea hubs löschen (das keine falschen  Daten reinkommen mit abgeschnittenen IDs). Dann starten.

Nehme bitte in jedem Fall wieder euine neues Debug log wie oben ... Auch wenn alles tut zum verifizieren! Danke

**Comment by ronschd** [comment]
Hey,

habe den aktuellen Adapter von GitHub installiert und neu gepaired.
Dann den Adapter einmal normal gestartet und bekomme jetzt updates der Werte, soweit ich gesehen habe im polling Interval.

Habe dann den Adapter nochmal im Debug gestartet und Rollos rauf und runtergefahren.
Log dazu im Anhang.
[debug_2023_01_10_01_31.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10377942/debug_2023_01_10_01_31.log)

Hoffe es hilft dir.

Vielen Dank für deine schnellen Reaktion und das fixing.

lg R

**Comment by ronschd** [comment]
Wenn ich noch etwas tun kann, gib einfach Bescheid.

**Comment by Apollon77** [comment]
Ja das ist ja schonmal Schritt 1 ... jetzt will ich nur noch wissen warum er dir subscriptions nicht mag ... 
Bitte nochmal Github installieren (musst aber nix unpairen oder löschen). Dann nochmal debug log bitte ... Er loggt jetzt das ergebnis des subscribe requests ... mal schauen was das sagt

**Comment by ronschd** [comment]
Geht klar.
Sorry für die unwissende Frage.
Wie wäre der richtige Weg einen über GitHub installierten Adapter zu aktualisieren?

**Comment by ronschd** [comment]
Okok, einfach drüberinstallieren.

Hab ich jetzt mal gemacht und die Instanz im Debug laufen lassen.
Log wieder angehängt.

[debug_2023_01_10_10_54.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10381322/debug_2023_01_10_10_54.log)

lg R

**Comment by Apollon77** [comment]
Hi,
hm ... kannst bitte nochmal? Musste nochmal was ändern das das logging kommt was ich sehen will :-)

**Comment by ronschd** [comment]
Hey,

ja klar. =)
Anbei wieder das Log.
[debug_2023_01_10_12_05.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10381921/debug_2023_01_10_12_05.log)

lg R

**Comment by Apollon77** [comment]
und der hoffentlich jetzt bitte  letzte versuch ... beim subscriben auf die states wurden die "hohen zahlen" wieder kaputt gemacht :-)

**Comment by ronschd** [comment]
Hey,

ich glaub fast, du hast recht =)
Werte kommen jetzt nicht mehr nur in den polling intervallen, sondern werden bei Änderung sofort aktualisiert.
Und es funktioniert jetzt auch, dass man Werte in Richtung Rollo bekommt, also steuern funktioniert jetzt auch sehr fein.

Wie meinst du die "hohen Zahlen" ?

Anbei natürlich wieder ein Debug Log
[debug_2023_01_10_13_36.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/10382799/debug_2023_01_10_13_36.log)

Kann man eigentlich auch im Expertenmodus einfach das Logging auf Debug umstellen ?
Also ohne die Instanz über die Konsole zu starten ?

Aja, und falls ich dir nochmal was testen kann, einfach sagen.

Vielen Dank, schaut wunderbar aus.

lg R

**Comment by Apollon77** [comment]
Jupp, genaauuuu so mag ich das Log :-) Checke noch paar Dinge und dann gibts ein update, aber du kannst erstmal so nutzen

**Comment by ronschd** [comment]
Haha, ja auch die Funktion mag ich so =)
Perfekt, nochmals vielen Dank!
Falls du nochmal Tests brauchst vom Dirigera, gib einfach Bescheid.

lg R
