### ISSUE TITLE
Wrong IP for the device

### ISSUE THREAD

**Issue by Draygv2** [Apollon77/ioBroker.homekit-controller#267]
I had a rogue DHCP Server in my network who gave the homekit device a wrong IP. No it seams to be saved some where in the instance. If I change the IP in the object folder nothing change.
Is there any place where I can change the IP? Or something else I can do to reach the device again?

the protocol gave me this:
```
<html>
<body>
<!--StartFragment-->

debug | Service: {"name":"VELUX Gateway","address":"192.168.115.8","port":5001,"c#":15,"ff":1,"id":"","md":"VELUX Gateway\u0000","pv":"1.1","s#":1,"sf":0,"ci":2,"availableToPair":false}
-- | --


<!--EndFragment-->
</body>
</html>
```

and later a timeout. Make sense this IP is not valid.

**Comment by Apollon77** [comment]
Which adapzter version do you use? There is 0.5.7 in Beta that should optimize in such cases. Please try this version. If still not helps I need a full debug log with info on right and pot wrong IPs

**Comment by Draygv2** [comment]
I use 0.5.1. I'll try it.

**Comment by Draygv2** [comment]
It worked with 0.5.7. Many thanks.
