### ISSUE TITLE
Ikea Dirigerga ist verbunden - Homekit-controller reagiert nicht auf Änderungen

### ISSUE THREAD

**Issue by Sur-De** [Apollon77/ioBroker.homekit-controller#271]
Hallo,

ich habe das Ikea Dirigera in der Firmware-Version (2.256.3) und den Homekit-Controller (0.5.1).

Nach den pairen werden zwar Einträge zu den in Dirigera angelegten Ikea-Geräten erzeugt, aber die Werte (true/false) der Geräte scheinen nicht upzudaten.

Setze ich einen Wert (bspw. Lampe "OUTLET-.ON" auf true) wird der Eintrag sofort wieder auf false gesetzt.
Das Gerät OUTLET wird nicht gesteuert.

Einen Eintrag im LOG gibt es ebenfalls nicht für diesen Schaltvorgang.

Wenn der Dirigera-Hub mit Apple-Homekit (iPhone) verbunden ist, sind die Geräte steuerbar und legen auch Werte-Updates.

Ist der Fehler bereits bekannt?

Grüße
Sur.

**Comment by Apollon77** [comment]
Please use the latest beta version --> https://github.com/Apollon77/ioBroker.homekit-controller#057-2023-01-27
