### ISSUE TITLE
Devices gets added multiple times

### ISSUE THREAD

**Issue by jniclas** [Apollon77/ioBroker.homekit-controller#283]
**Describe the bug**  
A temperature sensor lost the connection to my Aqara E1 Hub and after adding it again, it appears twice in iobroker. Although the serial number keeps the same.

**To Reproduce**  
1. wait till sensor has lost connection
2. add again
3. see the device twice in iobroker

**Expected behavior**  
The device should only show up once in iobroker

**Screenshots & Logfiles**
You can see that device 44 and 45 have the same serial-number
![image](https://github.com/Apollon77/ioBroker.homekit-controller/assets/36968958/f2a148df-65d9-4053-8b66-d06f4442ff42)

**Versions:**  
 - Adapter version: v0.5.8
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: linux

**Comment by Apollon77** [comment]
The ids are returned that way from the hub, so the adapter can not do anything. Only we can do is to cleanup "old" states. It for now I decided against it.
