### ISSUE TITLE
Could not initialize device: TimeoutError: at Object.<anonymous>

### ISSUE THREAD

**Issue by aer0xkh** [Apollon77/ioBroker.homekit-controller#287]
Hi i got a Velux Gateway and got these errors:

<html>
<body>

homekit-controller.0 | 2023-06-23 07:49:59.138 | warn | Device IP-25:86:3F:E3:A0:97 had too many errors, reinitialize connection
-- | -- | -- | --
homekit-controller.0 | 2023-06-23 07:48:17.913 | warn | IP-25:86:3F:E3:A0:97 Could not initialize device: TimeoutError: at Object.<anonymous> (/opt/iobroker/node_modules/@esm2cjs/p-queue/build/esm/index.js:16:22) at Module._compile (node:internal/modules/cjs/loader:1196:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10) at Module.load (node:internal/modules/cjs/loader:1074:32) at Function.Module._load (node:internal/modules/cjs/loader:909:12) at Module.require (node:internal/modules/cjs/loader:1098:19) at require (node:internal/modules/cjs/helpers:108:18) at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js:43:35) at Module._compile (node:internal/modules/cjs/loader:1196:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)

</body>
</html>

When i restart the adapter, these issue is still there but i can control the windows for an couple of hours.

**Comment by Apollon77** [comment]
Please provide a full debug log. SUch log excerts are mot that helpful.

Otherwise: Did you tried powering off/on the device? Normally this error measn that the devcie i simply not responding because of bad Wifi or other issues

**Comment by aer0xkh** [comment]
i placed it nearer to the access point, since 12:15 no error. thanks for the hint.
