### ISSUE TITLE
IP Discovery with mulithost environment

### ISSUE THREAD

**Issue by marc577** [Apollon77/ioBroker.homekit-controller#289]
I'm trying to connect the Aqara FP2 presence Sensor. My setup is a master docker iobroker host in my trunk vlan via macvlan and an iobroker mulithost slave docker instance in an iot vlan also via macvlan network Interface (only this network adapter is connected to this host) where also the sensor is connected to. The homekit controller adapter instance is running on the slave host in the iot net. 
Sadly the discovery of the instance only shows devices of the masters network. 

Is this the expected behavior? 
Or is it possible to change the discovery subnet or change the network Interface which the discovery is using? 

**Versions:**  
 - Adapter version: 0.5.8
 - JS-Controller version: 5.0.7
 - Node version: 18.16.1
 - Operating system: Debian bullseye docker

**Comment by Apollon77** [comment]
Are you then sure that the instance runs on the correct host? because in fact in my expectation the slave host in the "other" network should only see stuff from the "other" network. SO check that the instance is assigneed to the correct host.

**Comment by Apollon77** [comment]
no answer, closed
