### ISSUE TITLE
Aqara FP2 Proxmox no pairing

### ISSUE THREAD

**Issue by StefanTR96** [Apollon77/ioBroker.homekit-controller#290]
**Describe the bug**  
Got my Aqara FP2 and conected it to my homenetwork. I also find it as an device in the homekit-controller. There is the eye symbol at discovered but no button to connect as I saw in tutorial videos. I connected the device on my iphone and deleted the device in the home app. 

**Screenshots & Logfiles**  
`IP-A2:4C:4B:FA:66:02 (Presence-Sensor-FP2-4207) found without known pairing data and already paired: ignoring`

**Versions:**  
 - Adapter version: 0.5.8
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: Debian Bullseye in Proxmox LXC

**Additional context**  
iobroker is running in a LXC on Proxmox

**Comment by StefanTR96** [comment]
After hours of trying and restarting the device around 30 times the pairing symbol got visible and everything works.

**Comment by Apollon77** [comment]
In fact the log message showed exactly the reason why it was not available for pairing. The device itself announced that it is already paired and Homekit can only pair with one controller
