### ISSUE TITLE
Aqara in different subnet not reachable

### ISSUE THREAD

**Issue by MiDoTr** [Apollon77/ioBroker.homekit-controller#308]
Hi,

I have ioBroker running with homekit-controller and successfully paired an Aqara (FP2) device with both iobroker and aqara being in the same network "A". 

I want to use Aqara at another location "B" with an own network. Both networks A (192.168.178.0/24) and B (192.168.22.0/24) are connected trough a constant VPN tunnel and can communicate among each others. Also both locations A and B have WiFi with the same SSID and password. 

The Aqara device successfully connects to the WiFi at location B, it also shows as available and functioning in the Aqara app. ioBroker/homekit-controller can't find it though.

I changed the IP-value [.../info/addess] of the object in ioBroker - which didn't seem to make any difference, connection was still made to the .178.xx IP of network A which was stored after pairing the device. So I hardcoded the new IP address .22.xx of network B in node_modules\iobroker.homekit-controller\build\main.js to try it out, debug log shows that the connection is going out to the correct IP from network B. But - it times out.

So my question is now, whether I am missing something or if what I want to achieve isn't possible at all. I understand this is more of a support request than an issue/bug, but I hope I can get some help or at least a pointer in the right direction here. 

Cheers
Michael

**Comment by Apollon77** [comment]
The whole Homeklit discovery of devices works via MDNS ... So you need to make sure that this is roiuted between your two networks (which is not default case).

**Comment by MiDoTr** [comment]
I see, thank you a lot for the pointer. Need to find out if I can make my Vigors pass mDNS.
Yes, noticed that the port changed (had to portscan the device to find the open port), but that made no difference, either. 

But I have a clue now in which direction to look, so thanks again.
