### ISSUE TITLE
Configuration Page empty

### ISSUE THREAD

**Issue by Joylancer** [Apollon77/ioBroker.homekit-controller#310]
Hi,
thx for this adapter.
Version 0.5.8 shows all Entrys in Configuration page.
Version 0.5.9 works with this enabled Entry, but Configuration-Window is empty.
(no add, save, cancel ...)(Aquara FP2 enabled in 0.5.8 works)
nodejs: 18.19.0
npm: 10.2.3
debian bookworm
can you help?

**Comment by Sniks6** [comment]
Same here. Just freshly installed version 0.5.9.
Config page doesn't show anything. It's completely empty.

Node.js v18.18.2 
NPM 9.8.1

Admin v6.12.9


Any hints?

**Comment by Apollon77** [comment]
Is the javascriot console showing any error?

**Comment by Joylancer** [comment]
no, no errors, debug also no error, 
when I compare the files on Git with the locals, some are new and some are not. The .html, JS and JS.map remain at version 0.5.8 despite the update.

**Comment by Garfonso** [comment]
> Is the javascriot console showing any error?

yes. This is the error output I get:
![Screenshot_Developer Tools — intro - ioBroker — http:__server:8081_#tab-intro_1](https://github.com/Apollon77/ioBroker.homekit-controller/assets/620860/b1557dc7-c281-4347-9792-31c65881e46c)

This is the link the error message states: https://legacy.reactjs.org/docs/error-decoder.html/?invariant=321

Something about a problem with a hook. One of reasons hint to mismatching react versions... hm

**Comment by simpixo** [comment]
same here. any updates on this issue?

**Comment by Siot** [comment]
![imagen](https://github.com/Apollon77/ioBroker.homekit-controller/assets/4410120/17db5082-2f5b-4fc1-86bb-f4ac03c894fb)

From docker console

**Comment by Apollon77** [comment]
@Siot COmpletely different error. update to latest version

**Comment by Siot** [comment]
@Apollon77 I'm using the latest version:
![imagen](https://github.com/Apollon77/ioBroker.homekit-controller/assets/4410120/d49f251d-0804-469b-8a38-612f61abc44e)
And the previous error screenshot is from the latest version.

But I think you are right, the error doesn't appears exactly when I navigate to Instance Settings.

Thank you.

**Comment by Apollon77** [comment]
Then still a different issue (please create another one) and add a debug log with such an error

**Comment by bruesche** [comment]
Hi there, 
have same error "empty configuration site". Deinstalled the adapter and installed the adapter fresh. Configuration site doesn't work. implemented devices are working well, but can't apply the devices. 
is there a fix or a workaround?

Thx for help

**Comment by bruesche** [comment]
> Hi there, have same error "empty configuration site". Deinstalled the adapter and installed the adapter fresh. Configuration site doesn't work. implemented devices are working well, but can't apply new devices. is there a fix or a workaround?
> 
> Thx for help

By the way. Have same entry in DEV Tools from Browser like Garfonso. If i can help to solve the Problem  - you are welcome. Let me know please.

**Comment by Siot** [comment]
@Apollon77 *.map files would be very useful to debug in browser. Could you remove from .npmignore?

I have tried `DEBUG=hap* node /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js 0 --debug --logs` but there are no errors.

**Comment by bruesche** [comment]
> @Apollon77 *.map files would be very useful to debug in browser. Could you remove from .npmignore?
> 
> I have tried `DEBUG=hap* node /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js 0 --debug --logs` but there are no errors.

Tried it too. No error in debug mode. Only error in web browser console. Tried to start settings page, see shortly the iobroker logo and than an empty page.

**Comment by TecTom0815** [comment]
I have the same issue. On the settings Page i also see the Logo for a view secs and than an empty Page. Not able to do settings or add any device.

**Comment by Hanshauser** [comment]
Same problem here. The setting-page is empty.

**Comment by Apollon77** [comment]
Please try 0.5.10

**Comment by Hanshauser** [comment]
> Please try 0.5.10

Great. With 0.5.10 the setting-page is visible and everything works fine. Thanks a lot.
