### ISSUE TITLE
Seite Instanzeinstellungen bleibt leer

### ISSUE THREAD

**Issue by DEV2DEV-DE** [Apollon77/ioBroker.homekit-controller#318]
Mit Version 0.5.9 bleibt die Seite mit den Instanzeinstellungen leer.
Nach Downgrade auf 0.5.8 geht's wieder.
Wieder zurück auf die 0.5.9: Seite bleibt leer.
Das Ganze mit verschiedenen Browsern getestet ( Chrome, FF, Edge, Safari)

```
JS-Controller: 5.0.17
Node.js: v18.19.0
NPM: 10.2.3
```

**Comment by BigChris** [comment]
```
Das gleiche bei mir.
Node.js: v18.17.1
NPM: 9.6.7
```

**Comment by Apollon77** [comment]
Install Beta 0.5.10
