### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by cherberg** [Apollon77/ioBroker.homekit-controller#323]
**Describe the bug**  
Der Adapter startet bei mir leider nicht richtig. Die Instanz bleibt gelb, die Konfigurationsseite zeigt keinerlei Inhalte. In der ios App Home wird keine Steuerzentrale angezeigt.

**To Reproduce**  
Installiere Adapter Version 0.5.9. 
Prüfe den Status unter Instanzen
Prüfe die Verfügbarkeit der Konfigurationsseite

**Expected behavior**  
Adapter sollte starten

**Screenshots & Logfiles**  
Die Installation des Adapters läuft erfolgreich und endet mit Code 0.
Die Konfigurationsseite des Adapters erscheint, das iobroker Logo flackert kurz auf, es sind jedoch keine Inhalte vorhanden
Die Instanz zeigt Status Gelb.

Protokolleinträge des Adapterstarts:
`homekit-controller.0 | 2024-02-11 21:09:24.186 | debug | state homekit-controller.0.info.connection changed: false (ack = true)
-- | -- | -- | --
homekit-controller.0 | 2024-02-11 21:09:24.018 | info | starting. Version 0.5.9 in /opt/iobroker/node_modules/iobroker.homekit-controller, node: v18.16.0, js-controller: 5.0.16
homekit-controller.0 | 2024-02-11 21:09:23.810 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
homekit-controller.0 | 2024-02-11 21:09:23.800 | debug | Plugin sentry Initialize Plugin (enabled=true)
homekit-controller.0 | 2024-02-11 21:09:23.702 | debug | States connected to redis: 127.0.0.1:9000
homekit-controller.0 | 2024-02-11 21:09:23.630 | debug | States create User PubSub Client
homekit-controller.0 | 2024-02-11 21:09:23.628 | debug | States create System PubSub Client
homekit-controller.0 | 2024-02-11 21:09:23.590 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
homekit-controller.0 | 2024-02-11 21:09:23.512 | debug | Objects connected to redis: 127.0.0.1:9001
homekit-controller.0 | 2024-02-11 21:09:23.503 | debug | Objects client initialize lua scripts
homekit-controller.0 | 2024-02-11 21:09:23.385 | debug | Objects create User PubSub Client
homekit-controller.0 | 2024-02-11 21:09:23.383 | debug | Objects create System PubSub Client
homekit-controller.0 | 2024-02-11 21:09:23.380 | debug | Objects client ready ... initialize now
homekit-controller.0 | 2024-02-11 21:09:23.283 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
homekit-controller.0 | 2024-02-11 21:09:18.387 | info | terminating
homekit-controller.0 | 2024-02-11 21:09:17.885 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
homekit-controller.0 | 2024-02-11 21:09:17.884 | debug | Plugin sentry destroyed
homekit-controller.0 | 2024-02-11 21:09:17.881 | info | terminating
homekit-controller.0 | 2024-02-11 21:09:17.870 | info | Got terminate signal TERMINATE_YOURSELF`

Screenshot der Konfigurationsseite:
![image](https://github.com/Apollon77/ioBroker.homekit-controller/assets/8701752/82a705e6-6f90-48a5-b68c-7c01e50d7e9f)

Status Adapterinstanz:
![image](https://github.com/Apollon77/ioBroker.homekit-controller/assets/8701752/5df9bea2-dce0-4065-a224-aabdc2f0d66e)

Objekte:
![image](https://github.com/Apollon77/ioBroker.homekit-controller/assets/8701752/56190a95-0558-43a7-a02a-feca42c55ddf)

Adapter Version 0.5.8 zeigt zumindest die Konfigurationsseite und erkennt auch Geräte (yahka Bridge) jedoch erscheint es nicht als Steuerzentrale in der ios Home App
Adapter Version 0.5.10 zeigt zumindest die Konfigurationsseite und erkennt auch Geräte (yahka Bridge) jedoch erscheint es nicht als Steuerzentrale in der ios Home App

**Versions:**  
 - Adapter version: 0.5.9
 - JS-Controller version: 5.0.16
 - Node version: 18.16.0
 - Operating system: raspbian

**Additional context**

**Comment by Apollon77** [comment]
Bitte 0.5.10 nutzen ... ggf noch im Beta.
Ohne Geräte ist "gelb" korrekt.  UI ist mit 0.5.10 gefixt
