### ISSUE TITLE
Aqara FP2 Einstellungen per Adapter triggern?

### ISSUE THREAD

**Issue by Schmetterfliege** [Apollon77/ioBroker.homekit-controller#339]
Ich nutze den homekit-controller rein für die Integration meiner Aqara FP2.
Funktioniert soweit wunderbar, allerdings soweit ich das sehe hört der Adapter nur zu.
In den Objekten gibt es allerdings die Möglichkeit "unpair" zu triggern.

Daher wäre meine Frage: wäre es auch möglich über den Adapter andere Aktionen auszuführen, wie zb. Einstellungen?

Hintergrund: Der Sensor funktioniert ...solala und erkennt manchmal nicht wenn ich den Raum verlasse, und das Licht bleibt an.
Das Licht kann ich per Skript steuern, allerdings ist es dann auch immer nötig in die Aqara App zu gehen und "Ai Learning" zu triggern, wodurch der Status auf "Absence" gesetzt wird und er den Raum neu anlernt.
Besteht die technische Möglichkeit diese Option auch über den Adapter zu triggern?

**Comment by Apollon77** [comment]
Der Adapter stellt alle Homekit Daten bereit, wenn da also nichts drin ist dann ist das "Herstellerspezifisch" und der Hersteller macht mit seiner App eigenen kram. Wenn also da nichts drin ist dann nein
