### ISSUE TITLE
Homekit Velux Regensensor

### ISSUE THREAD

**Issue by Xells1984** [Apollon77/ioBroker.homekit-controller#341]
Hi,

Ich nutze den Homekit Adapter für mein Velux Gateway mit Dachfenster inkl. Regensensor.

Da das so schön lokal ohne cloud läuft ist das Perfekt.

Im Velux Adapter über die Cloud kommt noch die Information mit ob es aktuell regnet. Ist es möglich dies über den Homekit Adapter mit Abzufragen?

Gruß 

Hi,

I use the homekit Adapter for my Velux Roof Sensor with rain Detektion.

In the velux Adapter via cloud I get the Information of its raining.

But it would ne awesome of I could get this Information local instead via cloud. 

Is this possible?

Best Regards

**Comment by Apollon77** [comment]
The adapter works generically and parses the data available in the Homekit data from the device. SO if it is not in then no ... check the log if there is maybe a logging about unknown data, but else nope
