### ISSUE TITLE
cant upgrade from 0.5.8

### ISSUE THREAD

**Issue by tiigaaa** [Apollon77/ioBroker.homekit-controller#376]
Hello,

today i  tried to upgrade from 0.5.8 > 0.5.11
But I run into an Error. :(
I tried also to delete the Adapter and reinstll but same error.
Have somebody the same issue? Can somebody help me?

npm verion =  10.5.0
node verion = v21.7.3
python verion = 3.11.2 >>maybe this is the issue? I will try to upgrade
OS = Debian 12 on proxmox

After "**iob nodejs-update**" (see next post)
npm verion =  10.8.2
node verion = v20.18.1
python verion = 3.13 manuall install

Still same issue

Many thanks
BR

user@FHEM-SERVER:/opt/iobroker/node_modules# iobroker upgrade  "homekit-controller" --debug

This upgrade of "homekit-controller" will introduce the following changes:
==========================================================================
-> 0.5.11:
Stability and compatibility improvements for BLE

-> 0.5.10:
Fix user interface

-> 0.5.9:
Prevent crash when a single value is returned as error status
send booleans always as 0/1 to make sure all devices handle it correctly
Update dependencies
==========================================================================

Would you like to upgrade homekit-controller from @0.5.8 to @0.5.11 now? [(y)es, (n)o]: y
Update homekit-controller from @0.5.8 to @0.5.11
NPM version: 10.5.0
Installing iobroker.homekit-controller@0.5.11... (System call)
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated gauge@2.7.4: This package is no longer supported.

> @stoprocent/bluetooth-hci-socket@1.4.1 install
> node-gyp-build

> @stoprocent/noble@1.15.1 install
> node-gyp-build

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@21.7.3 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
(node:322383) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/opt/iobroker/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /opt/iobroker/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:193:23)
gyp ERR! System Linux 6.1.0-28-amd64
gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/@stoprocent/noble
gyp ERR! node -v v21.7.3
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! code 7
npm ERR! path /opt/iobroker/node_modules/@stoprocent/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-13T21_35_28_464Z-debug-0.log
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated npmlog@4.1.2: This package is no longer supported.
npm WARN deprecated are-we-there-yet@1.1.7: This package is no longer supported.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated gauge@2.7.4: This package is no longer supported.
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@21.7.3 | linux | x64
gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
(node:322383) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/opt/iobroker/node_modules/node-gyp/lib/configure.js:117:21)
gyp ERR! stack     at /opt/iobroker/node_modules/node-gyp/lib/configure.js:84:9
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:193:23)
gyp ERR! System Linux 6.1.0-28-amd64
gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/@stoprocent/noble
gyp ERR! node -v v21.7.3
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
npm ERR! code 7
npm ERR! path /opt/iobroker/node_modules/@stoprocent/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-12-13T21_35_28_464Z-debug-0.log
host.FHEM-SERVER Cannot install iobroker.homekit-controller@0.5.11: 7
user@FHEM-SERVER:/opt/iobroker/node_modules#

From the LOG:

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.5.0
2 info using node@v21.7.3
3 timing npm:load:whichnode Completed in 6ms
4 timing config:load:defaults Completed in 8ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 3ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 10ms
8 timing config:load:env Completed in 2ms
9 timing config:load:file:/opt/iobroker/node_modules/iobroker.info/.npmrc Completed in 0ms
10 timing config:load:project Completed in 20ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 50ms
17 timing npm:load:configload Completed in 51ms
18 timing config:load:flatten Completed in 10ms
19 timing npm:load:mkdirpcache Completed in 11ms
20 timing npm:load:mkdirplogs Completed in 3ms
21 verbose title npm
22 verbose argv "--version"
23 timing npm:load:setTitle Completed in 4ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2024-12-13T21_43_02_608Z-
26 verbose logfile /home/iobroker/.npm/_logs/2024-12-13T21_43_02_608Z-debug-0.log
27 timing npm:load:logFile Completed in 21ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 1ms
30 timing npm:load Completed in 160ms
31 verbose exit 0
32 timing npm Completed in 183ms
33 info ok

**Comment by tiigaaa** [comment]
phyton upgrade to 3.13 same issue

I also checked the system with the "iob nodejs-update " command, and it looks ok.
But i said "y" to switch to the recommended version 20.18.1 but this also did not fix the issue




Recommended nodejs-version is: 20.18.1
Checking your installation now. Please be patient!

Your current setup is:
/usr/bin/nodejs         v21.7.3
/usr/bin/node           v21.7.3
/usr/bin/npm            10.5.0
/usr/bin/npx            10.5.0
/usr/bin/corepack       0.25.2

We found these nodejs versions available for installation:

nodejs:
  Installed: 21.7.3-1nodesource1
  Candidate: 21.7.3-1nodesource1
  Version table:
 *** 21.7.3-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
        100 /var/lib/dpkg/status
     21.7.2-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.7.1-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.7.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.6.2-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.6.1-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.6.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.5.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.4.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.3.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.2.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.1.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     21.0.0-1nodesource1 600
        500 https://deb.nodesource.com/node_21.x nodistro/main amd64 Packages
     18.19.0+dfsg-6~deb12u2 500
        500 https://ftp.debian.org/debian bookworm/main amd64 Packages
     18.19.0+dfsg-6~deb12u1 500
        500 https://security.debian.org/debian-security bookworm-security/main amd64 Packages



Nothing to do - Your installation is using the correct paths.

You are running nodejs v21.7.3. Do you want to install recommended version 20.18.1?

Press <y> to continue or any other key to quit

**Comment by tiigaaa** [comment]
JIPIII,
after upgrading node-gyp "https://github.com/nodejs/node-gyp/releases" I was albe to upgrade the adapter.
![image](https://github.com/user-attachments/assets/97491cc0-dd98-4304-a28f-084edb4f2543)


Can be closed!

**Comment by Apollon77** [comment]
Great you figured out yourself
