### ISSUE TITLE
Connection to host lost

### ISSUE THREAD

**Issue by Draygv2** [Apollon77/ioBroker.homekit-controller#67]
Hi 
after some days the instance lose the connection to the host.

Log:
<html><body>

homekit-controller.0 | 2021-12-17 03:16:06.626 | info | Device IP-xxxxxx data polling failed: connect EHOSTUNREACH 10.2.2.45:5001
-- | -- | -- | --

</body>
</html>

After a restart of the instance everything is running well.

**Comment by Apollon77** [comment]
EHOSTUNREACH means that the device is not available in your network ... so czeck the WLAN settings and make sure the device is in the network with this IP. Could it be that the IP changed? Or what is it?

**Comment by Draygv2** [comment]
The device have a fixed IP in the same network and I use it also with the Velux adapter and that one give no problem. It is a Velux Gateway.

**Comment by Apollon77** [comment]
Try to login to the iobroker host and do a "ping" to the IP ot a "telnet" to the IP and port ... does it work? As said the error is from" network level" that he host was not reacable at this timepoint

**Comment by Draygv2** [comment]
The ping the the IP is no problem.

With the port I have connection

root@iobroker-produktiv:~#` telnet 10.2.2.45 5001
Trying 10.2.2.45...
Connected to 10.2.2.45.
Escape character is '^]'.
^[
HTTP/1.1 503 Service Unavailable
Content-Type: application/hap+json
Content-Length: 17

{"status":-70403}Connection closed by foreign host.

From where did the adapter take the port

**Comment by Apollon77** [comment]
That would help!

maybe there are short times of wlan issues that affect it ... But the adapter should reconnect. If this do not work a debug log would be cool that I see whats up

**Comment by Draygv2** [comment]
I have the problem at the moment.
telnet could connect
root@iobroker-produktiv:~# telnet 10.2.2.45 5001
Trying 10.2.2.45...
Connected to 10.2.2.45.
Escape character is '^]'.
^CConnection closed by foreign host.

I had trouble to find the debug log with the new view of iobroker. Next time i will send the debug log.

**Comment by Draygv2** [comment]
Now the issue changed.
![grafik](https://user-images.githubusercontent.com/62559741/147214145-aeb1eed8-7233-4542-9fa3-f597717aae2f.png)
Nothing is in the log

**Comment by Apollon77** [comment]
Nothing?? There should be something when connection is lost

**Comment by Draygv2** [comment]
Now i know where to look. 
Hopefully you can find something

[homekit-controller.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/7773521/homekit-controller.txt)

**Comment by Apollon77** [comment]
When I see the log all is working as exoected ina case of a connection lost

* all was fine before 2021-12-24 03:00:30.275
* Then the device was no longer reachable (EHOSTUNREACH) ... so seems WLAN was off from the devices (both) OR the network of the host was broken or such
* then adapter tried to reconnect on each polling try ...
* 2021-12-24 03:01:18.150 he got a Velux discovery package, but communication was still not possible
* 2021-12-24 03:16:18.942 he got a Mi Home deiscovery package (but not paired to this instance)
* 2021-12-24 03:16:36.246 he got a Velux discovery package and reinitialized the device
* 2021-12-24 03:16:39.155 the connection status was set to "ok" again ...

So honestly ... I see nothing where the adapter behaves wrong. Why you have these EHOSTUNREACH problem is up to you to find in your network! Check when it happens ... if alwys 3:00-3:16 or such then try to find out why? Is there a router restart? is there anything else?

**Comment by Draygv2** [comment]
Yes, I restart my Wlan once a day. Otherwise the Veluxgateway logout after several days and I have to reconnect it manuelly. I had several calls with the velux support but they have no solution.

**Comment by Apollon77** [comment]
Ok ... but then ... anything is workng as expected or?! And yes sorry you will have these logs in your logfile

**Comment by Draygv2** [comment]
Oke the log is no problem as long as the instance is reconnect and running. Now its running since more than a week with no manually restart. Thats good.
Thanks for your help.

**Comment by Apollon77** [comment]
Cool :-)
