### ISSUE TITLE
Simultaneous control doesn't work

### ISSUE THREAD

**Issue by nemodil** [Apollon77/ioBroker.homekit-controller#82]
Hi,

If several objects are controlled in direct succession, either none or only one object reacts.

For example if I control the target position of one of my roller shutters to a certain value (manually or by script), this works perfectly. However, if I control several roller shutters in sequence by a script, either only one or only one roller shutter is controlled. 

However if I control each shutters with a delay of e.g. 500 ms, the control also works.

Automations in Homekit for more than one object results in the same issue.

I use
Linux on Raspberry Pi
Homekit Controller 0.0.31
JS-Controller 3.3.22
Node V14.18.2
 
![Script](https://user-images.githubusercontent.com/45435219/148280682-acc18097-350b-44c5-8aae-8a6fcfee8ab5.jpg)
![Objects](https://user-images.githubusercontent.com/45435219/148280717-18ae61f5-8c5e-4ed7-b4c4-9290ea0e68c9.jpg)
![log](https://user-images.githubusercontent.com/45435219/148280751-0eba0585-4537-43a9-ac19-2d9499dadcd0.jpg)

**Comment by Apollon77** [comment]
Please turn on debug loglevel and send lof of such a "simulatanous commands" ... in fact one Homekit device can handle one command at once, so the commands are queued ... in theory ... because I never could test that ... so log would help

**Comment by nemodil** [comment]
![log debug](https://user-images.githubusercontent.com/45435219/148284211-c156faea-7246-43a6-9321-f633d9678c56.jpg)

**Comment by Apollon77** [comment]
And now the hole think again please with some more data (a bit time before and a bit after) and as text :-) Thank you ... I only see the "results" of the set that went into an error ...

**Comment by Apollon77** [comment]
Or you knwo what ... lets go full debug.

* Stop adapter via admin
* open a shell
* run `DEBUG=hap* node /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js --logs --debug`
* now do the action
* send complete log please

**Comment by nemodil** [comment]
[log debug2.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/7818017/log.debug2.txt)

**Comment by nemodil** [comment]
[log debug3.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/7818020/log.debug3.txt)

**Comment by Apollon77** [comment]
Ok, I see the issue ... the queue is not working ... I'm checking

**Comment by nemodil** [comment]
Ok :-), but I forgot to add more commands into my script. If you need mode data, please let me know.

**Comment by Apollon77** [comment]
@nemodil want to try a pot fix?
edit /opt/iobroker/node_modules/iobroker.homekit-controller/build/main.js and change this line https://github.com/Apollon77/ioBroker.homekit-controller/blob/main/build/main.js#L503 ... change the number after concurrency from 10 to 1 ... does it work then? a new "full log" would be great.

**Comment by nemodil** [comment]
Okay, here's what I did:
I have controlled 7 shutters 7,8,12,13,15,16,20 and 2 blinds 19,22 from 100% to 80% and waited until all have reached 80%.
Then the same from 80% to 100%.
Then several times from 100% to 80% and back to 100% without waiting until the target position has been reached.
The controls were all processed sequentially :-)
Note: With the roller shutter / blind combination 15/22 and 20/19, only the roller shutter or blind can be moved at a given time.
[log debug4.txt](https://github.com/Apollon77/ioBroker.homekit-controller/files/7821830/log.debug4.txt)

**Comment by Apollon77** [comment]
@nemodil Would you be up for another test? I would like to try an other way of solving this ... Ok? Then please respond and I tell you what to do

**Comment by nemodil** [comment]
Of course I am, tell me what I have to do.

**Comment by Apollon77** [comment]
Sorry for the delay. Please update the adapter from GitHub and try your parallel case again. I would be happy to see such a "full debug" log (run from commandline) for it ...

**Comment by nemodil** [comment]
I installed the adapter from GitHub an got these errors:

$ iobroker url https://github.com/Apollon77/ioBroker.homekit-controller --host home
install Apollon77/ioBroker.homekit-controller#9fb9188e0fd289acb99437744f2caf2707c1dc60
NPM version: 6.14.15
npm install Apollon77/ioBroker.homekit-controller#9fb9188e0fd289acb99437744f2caf2707c1dc60 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! premature close
npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2022-01-14T22_25_42_746Z-debug.log
upload [10] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/js/runtime-main.f705f273.js static/js/runtime-main.f705f273.js application/javascript
upload [9] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/js/main.73ad8aca.chunk.js static/js/main.73ad8aca.chunk.js application/javascript
upload [8] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/js/2.e5a95dd3.chunk.js.LICENSE.txt static/js/2.e5a95dd3.chunk.js.LICENSE.txt text/plain
upload [7] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/js/2.e5a95dd3.chunk.js static/js/2.e5a95dd3.chunk.js application/javascript
upload [6] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/css/main.e2d673ee.chunk.css static/css/main.e2d673ee.chunk.css text/css
upload [5] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/static/css/2.faf2f676.chunk.css static/css/2.faf2f676.chunk.css text/css
upload [4] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/manifest.json manifest.json application/json
upload [3] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/index_m.html index_m.html text/html
upload [2] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/homekit-controller.png homekit-controller.png image/png
upload [1] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [0] homekit-controller.admin /opt/iobroker/node_modules/iobroker.homekit-controller/admin/asset-manifest.json asset-manifest.json application/json
Update "system.adapter.homekit-controller.0"
Process exited with code 0

**Comment by Apollon77** [comment]
Please try again, it seems that npm had an communication error while downloading the stuff

**Comment by nemodil** [comment]
[2022-01-15T01_05_44_155Z-debug.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/7874001/2022-01-15T01_05_44_155Z-debug.log)

**Comment by nemodil** [comment]
Multiple attempts to install the adapter lead to the same error message.

**Comment by Apollon77** [comment]
Mega strange ... can you please try again ... I tried something

**Comment by nemodil** [comment]
I tried to install the adapter from Github to a slave ioBroker …

$ iobroker url Apollon77/ioBroker.homekit-controller --host ioBroker5
install Apollon77/ioBroker.homekit-controller
NPM version: 6.14.15
npm install Apollon77/ioBroker.homekit-controller --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! premature close
npm ERR! A complete log of this run can be found in:
npm ERR! /home/iobroker/.npm/_logs/2022-01-16T12_11_25_858Z-debug.log
host.ioBroker5 Cannot install Apollon77/ioBroker.homekit-controller: 1
ERROR: Process exited with code 25

**Comment by Apollon77** [comment]
I do not understand why npm has issues here :-(( Ok, I will find another way and we retry with official release soon :-( Thnak you for your support

**Comment by Apollon77** [comment]
Ok, I just release new version, please check again and inform me if there are issues

**Comment by nemodil** [comment]
Hi,
So far everything works fine :-)))
I have no errors or warnings in my log.
Thanks a lot!
I only had a warning in the update log.
[Update.log](https://github.com/Apollon77/ioBroker.homekit-controller/files/7918084/Update.log)

**Comment by nemodil** [comment]
Hi,
Since last update I sometimes have these errors in the log

homekit-controller.0 | 2022-01-24 22:53:54.770 | info | Device IP-76:90:23:57:BD:54 data polling failed:
homekit-controller.0 | 2022-01-24 22:53:19.541 | info | Device IP-76:90:23:57:BD:54 data polling failed:
homekit-controller.0 | 2022-01-24 22:53:14.866 | info | Device IP-76:90:23:57:BD:54 data polling failed:
homekit-controller.0 | 2022-01-24 22:51:24.767 | info | Device IP-76:90:23:57:BD:54 data polling failed:

**Comment by nemodil** [comment]
A restart of the instance stops the polling failures and the adapter continues working normally

**Comment by Apollon77** [comment]
Very interesting ...I assume that it is a TimeoutError which would mean that the device did not answer ... I will add a check to also reset the connection in such a case

**Comment by Apollon77** [comment]
PS: next time please open new issue
